[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "llm_from_scratch"
version = "0.1.0"

[tool.setuptools]
packages = ["scripts"]   # explicitly tell setuptools only use scripts/
